from __future__ import annotations

import secrets
import time
from dataclasses import dataclass, field
from enum import Enum
from uuid import uuid4

# Temporary host-issued session token: 32 cryptographically random bytes
# (``secrets.token_urlsafe(32)`` → ~43 chars). Ephemeral, per-connection,
# never persisted. Distinct from the long-term provisioning credential.
SESSION_TOKEN_BYTES = 32
SESSION_TOKEN_ENCODING = "urlsafe-base64"


class ConnectionState(str, Enum):
    """Lifecycle states for an external TCP connection."""

    CONNECTED = "CONNECTED"
    TLS_ESTABLISHED = "TLS_ESTABLISHED"
    AUTHENTICATING = "AUTHENTICATING"
    AUTHENTICATED = "AUTHENTICATED"
    CLOSING = "CLOSING"
    CLOSED = "CLOSED"


@dataclass
class ConnectionSession:
    """
    Thread-safe mutable session record for one external TCP client.

    ``connection_id`` is a UUID generated by CORE and is distinct from
    ``identity_id`` (device identity). One device may hold multiple
    connections. Timestamps use ``time.monotonic`` seconds so tests can
    inject a fake clock.
    """

    connection_id: str = field(default_factory=lambda: str(uuid4()))
    remote_address: str = ""
    connected_at: float = field(default_factory=time.monotonic)
    authenticated_at: float | None = None
    # Wall-clock display strings for the lease triple sent to clients.
    # Enforcement always uses the monotonic ``lease_expires_at`` above.
    connected_iso: str | None = None
    lease_expires_iso: str | None = None
    identity_id: str | None = None
    authenticated: bool = False
    last_activity: float = field(default_factory=time.monotonic)
    lease_expires_at: float | None = None
    # Temporary host-issued session credential for this connection only.
    # Memory-only: never persisted, rotated every authentication, cleared
    # on any disconnect/expiry.
    session_token: str | None = None
    messages_received: int = 0
    messages_sent: int = 0
    state: ConnectionState = ConnectionState.CONNECTED

    def __post_init__(self) -> None:
        if not self.connection_id:
            raise ValueError("connection_id cannot be empty.")

    def touch(self, now: float | None = None) -> None:
        """Mark activity without changing authentication state."""
        self.last_activity = now if now is not None else time.monotonic()

    def mark_authenticated(
        self,
        identity_id: str,
        now: float | None = None,
    ) -> None:
        """Bind an authenticated device identity to this connection."""
        if not identity_id:
            raise ValueError("identity_id cannot be empty.")
        current = now if now is not None else time.monotonic()
        self.identity_id = identity_id
        self.authenticated = True
        self.authenticated_at = current
        self.last_activity = current
        self.state = ConnectionState.AUTHENTICATED

    def rotate_session_token(self) -> str:
        """Mint a fresh cryptographically random temporary session token."""
        token = secrets.token_urlsafe(SESSION_TOKEN_BYTES)
        self.session_token = token
        return token

    def clear_session_token(self) -> None:
        """Invalidate the temporary session token (disconnect/expiry)."""
        self.session_token = None

    def start_lease(self, lease_seconds: float, now: float | None = None) -> None:
        """Start the authoritative connection lease at authentication time."""
        current = now if now is not None else time.monotonic()
        self.lease_expires_at = current + max(0.0, float(lease_seconds))

    def lease_remaining(self, now: float | None = None) -> float | None:
        """Return seconds until lease expiry, or None when no lease runs."""
        if self.lease_expires_at is None:
            return None
        current = now if now is not None else time.monotonic()
        return self.lease_expires_at - current

    def is_lease_expired(self, now: float | None = None) -> bool:
        """Return whether an active lease has expired (no lease: False)."""
        remaining = self.lease_remaining(now)
        return remaining is not None and remaining <= 0

    def transition(self, state: ConnectionState) -> None:
        """Move the session to a new lifecycle state."""
        self.state = state


__all__ = [
    "ConnectionSession",
    "ConnectionState",
    "SESSION_TOKEN_BYTES",
    "SESSION_TOKEN_ENCODING",
]
